"""rotquant -- rotation-based weight compression evaluation toolkit."""

__version__ = "0.1.0"

from .adapters import (
    AdapterRegistry,
    ModelAdapter,
    ModelSupport,
    get_model_adapter,
    inspect_model_support,
    list_model_adapters,
    register_model_adapter,
    resolve_model_adapter,
)
from .api import (
    RotQuantConfig,
    from_pretrained,
    inspect_model,
    optimize_model,
    save_pretrained,
)
from .block_train import (
    BlockCall,
    BlockRotationTrainConfig,
    TeacherCall,
    collect_block_calls,
    collect_teacher_calls,
    find_transformer_blocks,
    train_and_patch_blocks,
)
from .calibrate import (
    ActivationResult,
    HessianAccumulator,
    collect_activations,
    collect_hessians,
)
from .checkpoint import (
    checkpoint_manifest,
    load_packed_model,
    save_packed_checkpoint,
)
from .codebooks import (
    E8LatticeCodebook,
    ScalarCodebook,
    VectorCodebook,
    build_gaussian_vector_codebook,
    build_scalar_codebook,
    fit_scalar_codebook,
    fit_vector_codebook,
    lloyd_max_gaussian,
    lloyd_max_samples,
    lloyd_max_spherical,
    nearest_e8,
    normal_float,
    quantizer_mse,
    quantizer_mse_spherical,
    turboquant_mse_bound,
    uniform_signed,
)
from .dynamic import (
    DynamicQuantConfig,
    select_dynamic_quantization,
    teacher_logit_kl,
)
from .format import (
    CURRENT_PACKING,
    FORMAT_NAME,
    FORMAT_VERSION,
    OPTIMIZED_PROFILE_BITS,
    FormatValidationError,
    PackingContract,
    validate_checkpoint_manifest,
)
from .kv_cache import (
    KVQuantConfig,
    QuantizedKV,
    build_kv_rotation,
    kv_fidelity_metrics,
    kv_retrieval_metrics,
    quantize_kv,
    retrieval_rotquant_decode,
    rotquant_attention,
    train_kv_rotations,
)
from .linear import QuantLinear
from .native import (
    NATIVE_FORMAT_NAME,
    NATIVE_FORMAT_VERSION,
    NativeEncodedMatrix,
    NativeLayout,
    encode_quantized_weight,
    pack_native_blocks,
    reference_dequantize,
    reference_matmul,
    reference_streaming_matmul,
    unpack_native_blocks,
)
from .native_ffi import (
    NATIVE_C_ABI_VERSION,
    NativeKernelCapability,
    NativeRuntimeError,
    NativeRuntimeLibrary,
)
from .pack import PackedTensor, pack_indices, unpack_indices
from .patch import PATCH_MODES, PatchConfig, patch_model
from .quantize import QuantConfig, QuantizedWeight, Quantizer
from .rotate import (
    ButterflyRotation,
    DenseOrthogonal,
    Identity,
    LearnedRotation,
    RandomizedHadamard,
    Rotation,
    build_rotation,
    fwht,
)
from .runtime import (
    KERNELS,
    KernelRegistry,
    KernelSpec,
    run_kernel,
    runtime_capabilities,
)
from .train_rotation import (
    RotationTrainConfig,
    activation_reconstruction_error,
    select_butterfly_checkpoint,
    train_layer_rotation,
)
from .utils import (
    BitBudget,
    Timer,
    enable_default_logging,
    environment_record,
    get_logger,
    set_seed,
    write_result,
)

__all__ = [
    "CURRENT_PACKING",
    "FORMAT_NAME",
    "FORMAT_VERSION",
    "KERNELS",
    "NATIVE_C_ABI_VERSION",
    "NATIVE_FORMAT_NAME",
    "NATIVE_FORMAT_VERSION",
    "OPTIMIZED_PROFILE_BITS",
    "PATCH_MODES",
    "ActivationResult",
    "AdapterRegistry",
    "BitBudget",
    "BlockCall",
    "BlockRotationTrainConfig",
    "ButterflyRotation",
    "DenseOrthogonal",
    "DynamicQuantConfig",
    "E8LatticeCodebook",
    "FormatValidationError",
    "HessianAccumulator",
    "Identity",
    "KVQuantConfig",
    "KernelRegistry",
    "KernelSpec",
    "LearnedRotation",
    "ModelAdapter",
    "ModelSupport",
    "NativeEncodedMatrix",
    "NativeKernelCapability",
    "NativeLayout",
    "NativeRuntimeError",
    "NativeRuntimeLibrary",
    "PackedTensor",
    "PackingContract",
    "PatchConfig",
    "QuantConfig",
    "QuantLinear",
    "QuantizedKV",
    "QuantizedWeight",
    "Quantizer",
    "RandomizedHadamard",
    "RotQuantConfig",
    "Rotation",
    "RotationTrainConfig",
    "ScalarCodebook",
    "TeacherCall",
    "Timer",
    "VectorCodebook",
    "__version__",
    "activation_reconstruction_error",
    "build_gaussian_vector_codebook",
    "build_kv_rotation",
    "build_rotation",
    "build_scalar_codebook",
    "checkpoint_manifest",
    "collect_activations",
    "collect_block_calls",
    "collect_hessians",
    "collect_teacher_calls",
    "enable_default_logging",
    "encode_quantized_weight",
    "environment_record",
    "find_transformer_blocks",
    "fit_scalar_codebook",
    "fit_vector_codebook",
    "from_pretrained",
    "fwht",
    "get_logger",
    "get_model_adapter",
    "inspect_model",
    "inspect_model_support",
    "kv_fidelity_metrics",
    "kv_retrieval_metrics",
    "list_model_adapters",
    "lloyd_max_gaussian",
    "lloyd_max_samples",
    "lloyd_max_spherical",
    "load_packed_model",
    "nearest_e8",
    "normal_float",
    "optimize_model",
    "pack_indices",
    "pack_native_blocks",
    "patch_model",
    "quantize_kv",
    "quantizer_mse",
    "quantizer_mse_spherical",
    "reference_dequantize",
    "reference_matmul",
    "reference_streaming_matmul",
    "register_model_adapter",
    "resolve_model_adapter",
    "retrieval_rotquant_decode",
    "rotquant_attention",
    "run_kernel",
    "runtime_capabilities",
    "save_packed_checkpoint",
    "save_pretrained",
    "select_butterfly_checkpoint",
    "select_dynamic_quantization",
    "set_seed",
    "teacher_logit_kl",
    "train_and_patch_blocks",
    "train_kv_rotations",
    "train_layer_rotation",
    "turboquant_mse_bound",
    "uniform_signed",
    "unpack_indices",
    "unpack_native_blocks",
    "validate_checkpoint_manifest",
    "write_result",
]
